### ISSUE TITLE
bug: header is not fixed to top

### ISSUE THREAD

**Issue by GildasEdraE** [sanoojes/better-bloom#13] opened 2024-05-25 06:42 UTC
![Screenshot (138)](https://github.com/sanoojes/better-bloom/assets/89395504/49f91b99-3ae4-4e1f-b04a-5e3dff8a2bbb)
please I don't know how to fix this

**Comment by sanoojes** [comment] 2024-05-25 07:58
check the theme now it should be solved rn!

**Comment by sanoojes** [comment] 2024-05-25 08:04
![image](https://github.com/sanoojes/better-bloom/assets/93819264/4701ec0f-e359-461f-95d9-eda4450c62b8)
![image](https://github.com/sanoojes/better-bloom/assets/93819264/f7e638e7-7d9e-4dfa-bff8-24af2b1e81d8)

its should be like this now

**Comment by sanoojes** [comment] 2024-05-30 13:15
closed because of no reply from @GildasEdraE

**Comment by GildasEdraE** [comment] 2024-05-31 12:29
> ![image](https://private-user-images.githubusercontent.com/93819264/333782364-4701ec0f-e359-461f-95d9-eda4450c62b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTgwMzMsIm5iZiI6MTcxNzE1NzczMywicGF0aCI6Ii85MzgxOTI2NC8zMzM3ODIzNjQtNDcwMWVjMGYtZTM1OS00NjFmLTk1ZDktZWRhNDQ1MGM2MmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDEyMTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMTg5MDYzYjRjMmViMDcxNDQwZjY3OTA0YTE3Mjk2OTE1ZjA1ZGMwOWYwZDg4NGVjYjMyZjc0YjE0YWRlOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.96eVuiJ34zr3dajkQb16UAKMEw80ONYlqgVE-pj2yNs) ![image](https://private-user-images.githubusercontent.com/93819264/333782365-f7e638e7-7d9e-4dfa-bff8-24af2b1e81d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTgwMzMsIm5iZiI6MTcxNzE1NzczMywicGF0aCI6Ii85MzgxOTI2NC8zMzM3ODIzNjUtZjdlNjM4ZTctN2Q5ZS00ZGZhLWJmZjgtMjRhZjJiMWU4MWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDEyMTUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZDBkODAyMzc0NTczYzNkNDFlYzU2NTE1ZjUxNGNhMzEzNzk4MTQ0Y2I2MmMzMWVlNDZhMjQyYjY4MDA3ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2y5QB_yJNJu4CXqjLOMPCwE9DSVebi8umhTHp0HQ8S4)
> 
> its should be like this now

Idk, I'm give up

**Comment by GildasEdraE** [comment] 2024-05-31 12:33
> closed because of no reply from @GildasEdraE

Sorry @sanoojes, I'm not checking email, because I'm very busy in real life for now

**Comment by GildasEdraE** [comment] 2024-05-31 12:53
> check the theme now it should be solved rn!
> 
> if not fixed try this in powershell and comment the spotify version spicetify version and the extentions\apps installed sometimes that apps might me causing the issue
> 
> ```
> spicetify config inject_css 1 replace_colors 1 overwrite_assets 1 inject_theme_js 1
> spicetify apply
> ```

Wait, is there a settings feature that needs to  activating/deactivating?

**Comment by sanoojes** [comment] 2024-05-31 14:39
oo i see soory that i closed this issue ! i couldnt find what was the issue is the issue fixed ?

**Comment by sanoojes** [comment] 2024-05-31 14:45
i think it is the issue caused by the extensions or other apps ! 
check if the global nav is working in the experiments settings

![image](https://github.com/sanoojes/better-bloom/assets/93819264/487b630b-7fdc-4dd0-916a-a5b22caa5eb3)
![image](https://github.com/sanoojes/better-bloom/assets/93819264/13d274fa-45c3-437b-b701-6b82bf1ade11)

set to home-next-to-search

**Comment by GildasEdraE** [comment] 2024-06-01 11:25
> menurut saya ini adalah masalah yang disebabkan oleh ekstensi atau aplikasi lain! periksa apakah navigasi global berfungsi di pengaturan eksperimen
> 
> ![gambar](https://private-user-images.githubusercontent.com/93819264/335620936-487b630b-7fdc-4dd0-916a-a5b22caa5eb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDA5MjUsIm5iZiI6MTcxNzI0MDYyNSwicGF0aCI6Ii85MzgxOTI2NC8zMzU2MjA5MzYtNDg3YjYzMGItN2ZkYy00ZGQwLTkxNmEtYTViMjJjYWE1ZWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDExMTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNTUyMTI5YjgzNDk4YTBhMTQ2MjQzN2I3MTBkMTM1MzJlYTQ0YzEyNDNjZWVlNmY4MTI4MzBkYWVlMGE5NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cnWqTspGYsPHQVPfWbl8ft2ZtAS-T39TB8XjIzGvu0Q) ![gambar](https://private-user-images.githubusercontent.com/93819264/335620944-13d274fa-45c3-437b-b701-6b82bf1ade11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDA5MjUsIm5iZiI6MTcxNzI0MDYyNSwicGF0aCI6Ii85MzgxOTI2NC8zMzU2MjA5NDQtMTNkMjc0ZmEtNDVjMy00MzdiLWI3MDEtNmI4MmJmMWFkZTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDExMTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZjBjYzkxMGQ4N2I3YTM1OGIyNmVjMzNiOWFmMDVlMDE3N2U2Nzk3NmI4NDE0MWQ3NTQzMjM1ODE5YTkwNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jbR2bEgOD5ZfSb5OPoM5pXFv2uH4sY7dxC4Y4cloyKM)
> 
> disetel ke beranda-sebelah-untuk-penelusuran

![Screenshot (140)](https://github.com/sanoojes/better-bloom/assets/89395504/6ea84899-3a41-4670-82e3-e7377cc45afe)
Nice, I'm looks like a blind man.

**Comment by sanoojes** [comment] 2024-06-01 11:26
whattt is the spotify updated? it should be there in new ones

**Comment by sanoojes** [comment] 2024-06-01 11:28
try searching `home` also 
![image](https://github.com/sanoojes/better-bloom/assets/93819264/0608087a-7d86-4809-bb63-7e93e091c571)

**Comment by GildasEdraE** [comment] 2024-06-01 11:28
look doesn't work

**Comment by GildasEdraE** [comment] 2024-06-01 11:29
> try searching `home` also ![image](https://private-user-images.githubusercontent.com/93819264/335797597-0608087a-7d86-4809-bb63-7e93e091c571.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDE1ODQsIm5iZiI6MTcxNzI0MTI4NCwicGF0aCI6Ii85MzgxOTI2NC8zMzU3OTc1OTctMDYwODA4N2EtN2Q4Ni00ODA5LWJiNjMtN2U5M2UwOTFjNTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDExMjgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYmI0NTFiZTU5MjkwOGFlY2RmNmE0YzM2MDY1N2FhNGYzMTFhYzMwMGI2YjRkOGRjYWY0MWMyYjEwNTFkMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PTcdtKMeUxRzObwixjU3gRmSn-3c3cJKf5JU40pdHG0)

![Screenshot (141)](https://github.com/sanoojes/better-bloom/assets/89395504/f53fe847-0008-4c53-82ea-b0cdd907448f)
same

**Comment by sanoojes** [comment] 2024-06-01 11:31
what is the spotify and spicetify version try updating them and checkout

update spotify with newest exe
https://www.spotify.com/download/windows/

update spicetify 
```
spicetify update
```

**Comment by GildasEdraE** [comment] 2024-06-01 11:31
> what is the spotify and spicetify version try updating them and checkout
> 
> update spotify with newest exe https://www.spotify.com/download/windows/
> 
> update spicetify
> 
> ```
> spicetify update
> ```

yeah, I'm trying

**Comment by GildasEdraE** [comment] 2024-06-01 11:34
![Screenshot (142)](https://github.com/sanoojes/better-bloom/assets/89395504/2b46c658-a296-412d-9cb5-5c245c5ee8be)
can you check your spicetify version?

**Comment by sanoojes** [comment] 2024-06-01 11:35
Spotify for Windows (64 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11
Theme: better-bloom / dark
Extensions:
Custom apps: marketplace
xpui_2024-05-17_1715913620018_a4a70a0
cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Runtime: Chrome
Build System: CMake

**Comment by GildasEdraE** [comment] 2024-06-01 11:36
> Spotify for Windows (64 bit) 1.2.38.720.ga4a70a0e Spicetify v2.36.11 Theme: better-bloom / dark Extensions: Custom apps: marketplace xpui_2024-05-17_1715913620018_a4a70a0 cef_124.3.5+gff7dcd8+chromium-124.0.6367.119 Runtime: Chrome Build System: CMake

may be I'm gonna check spotify version

**Comment by sanoojes** [comment] 2024-06-01 11:38
can join our discord server ? it would be better

**Comment by GildasEdraE** [comment] 2024-06-01 11:39
> can join our discord server ? it would be better

where is link?

**Comment by GildasEdraE** [comment] 2024-06-01 11:41
sorry forgot that

**Comment by sanoojes** [comment] 2024-06-01 11:43
on our readme or use https://discord.gg/2tQWN8tP

**Comment by sanoojes** [comment] 2024-06-01 12:03
issue resolved ! it was because of the outdated spotify version now it works fine 
![image](https://github.com/sanoojes/better-bloom/assets/93819264/35426f42-afbe-4511-ae21-4490ce9f5012)

**Closed by sanoojes** 2024-06-01 12:03 UTC
Labels: invalid
